import type { ReferenceProduct } from "../schemas";

export const REFERENCE_PRODUCTS: ReferenceProduct[] = [
  {
    slug: "planet_rugby",
    name: "Planet Rugby",
    role: "first_party",
    url: "https://www.planetrugby.com",
    learnFrom: [
      "Match Centre layout",
      "Fixtures hub",
      "Results pages",
      "Competition and tournament navigation",
      "Team pages",
      "Live tables via SDMS widgets",
      "Match info tabs (lineups, stats, H2H)",
    ],
    doNotCopy: ["Proprietary HTML", "Widget bundles", "Editorial copy", "Crest assets without licence"],
    matchCentrePatterns: [
      "Header scoreboard with team crests",
      "Tabbed match centre (overview, lineups, stats)",
      "Embedded table/fixtures/results widgets per competition",
      "SDMS-backed live data with skeleton → hydrate pattern",
    ],
    commentaryPatterns: [
      "Live score-led updates",
      "Incident list alongside narrative",
      "Half-time and full-time status transitions",
    ],
    dataPatterns: ["SDMS match ID in page data attributes", "Competition code on widgets", "Team slug URLs"],
  },
  {
    slug: "sport365",
    name: "Sport365",
    role: "data_source",
    url: "https://www.sport365.com/rugby-union",
    learnFrom: [
      "Competition hierarchy in URLs",
      "Fixture list organisation",
      "Match page incident structure",
      "Live score and clock presentation",
      "__NEXT_DATA__ match object shape",
    ],
    doNotCopy: ["Commentary text from comms feed", "Proprietary incident copy", "Brand assets"],
    matchCentrePatterns: [
      "Score array [home, away]",
      "Period-grouped incidents (incs)",
      "Status code mapping (HT, FT)",
      "Scorer attribution from incident types",
    ],
    commentaryPatterns: [
      "Minute-ordered incident timeline",
      "Type-coded events (try, conversion, card)",
      "Score-after on each incident row",
    ],
    dataPatterns: ["External match ID (e.g. 1-4307586)", "Team pos 0/1", "Incident type integers"],
  },
  {
    slug: "espn_scrum",
    name: "ESPN Scrum",
    role: "reference_only",
    url: "https://www.espn.co.uk/rugby/",
    learnFrom: [
      "Commentary timeline UX",
      "Event ordering and grouping",
      "Minute formatting conventions",
      "Score update cadence",
      "Match summary structure",
      "Statistics and team comparison panels",
      "Player fact blocks",
    ],
    doNotCopy: [
      "Commentary sentences",
      "Match reports",
      "Journalist bylines",
      "Any editorial narrative text",
    ],
    matchCentrePatterns: [
      "Vertical timeline with event icons",
      "Key events clustered at score changes",
      "Half-time summary block",
      "Post-match facts section",
    ],
    commentaryPatterns: [
      "Immediate announcement on major events",
      "Shorter lines for set-piece restarts",
      "Score repeated after try + conversion pair",
      "Referee decisions isolated in timeline",
      "Substitution pairs grouped",
    ],
    dataPatterns: ["Event category labels", "Clock display with injury time"],
  },
  {
    slug: "statscore",
    name: "STATSCORE",
    role: "reference_only",
    learnFrom: [
      "Automated commentary event engine",
      "Widget embed architecture",
      "API-normalised event types",
      "Confidence and sequencing model",
      "Multi-sport event taxonomy patterns",
    ],
    doNotCopy: ["Widget code", "API keys", "Generated commentary strings", "Commercial SDK"],
    matchCentrePatterns: [
      "Event-driven widget updates",
      "Normalised event schema",
      "Period and clock sync",
    ],
    commentaryPatterns: [
      "Template-per-event-type automation",
      "Low-latency publish on state change",
      "Cooldown between similar events",
      "Auto vs operator-approved tiers",
    ],
    dataPatterns: ["Event type enum", "Widget payload JSON", "Pub/sub update channel"],
  },
  {
    slug: "all_rugby",
    name: "All.Rugby",
    role: "reference_only",
    url: "https://all.rugby",
    learnFrom: [
      "Club database structure",
      "Competition hierarchy",
      "Team parent/child relationships",
      "Player club affiliations",
      "Season and round modelling",
    ],
    doNotCopy: ["Database content", "Player bios", "Proprietary rankings copy"],
    matchCentrePatterns: ["Competition → season → round → fixture tree", "Club vs international team separation"],
    commentaryPatterns: [],
    dataPatterns: ["Entity IDs", "Competition tiers", "Squad relationships"],
  },
];
