import type { Rugby365TemplateFromResearch } from "../schemas";

/** Original Rugby365 templates derived from structural research — not copied from any provider. */
export const RUGBY365_RESEARCH_TEMPLATES: Rugby365TemplateFromResearch[] = [
  {
    templateKey: "try_scored",
    outputType: "major_event",
    tone: "celebratory",
    body: "{minute}' TRY! {team} — {phase_count} phases pays off.",
    eventTypes: ["try"],
    researchSource: "Synthesis: espn_scrum immediacy + sport365 score pairing",
    placeholders: ["minute", "team", "phase_count"],
  },
  {
    templateKey: "try_scored_alt",
    outputType: "major_event",
    tone: "celebratory",
    body: "{minute}' {team} score! {player} finishes in the corner.",
    eventTypes: ["try"],
    researchSource: "Synthesis: player attribution when fact present",
    placeholders: ["minute", "team", "player"],
  },
  {
    templateKey: "conversion_good",
    outputType: "major_event",
    tone: "factual",
    body: "{minute}' Conversion successful — {player}.",
    eventTypes: ["conversion"],
    researchSource: "Synthesis: post-try kicker naming",
    placeholders: ["minute", "player"],
  },
  {
    templateKey: "conversion_missed",
    outputType: "major_event",
    tone: "neutral",
    body: "{minute}' {team} miss the conversion.",
    eventTypes: ["conversion_missed"],
    researchSource: "Synthesis: low-weight miss line",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "drop_goal_scored",
    outputType: "major_event",
    tone: "factual",
    body: "{minute}' Drop goal! {player} extends the lead for {team}.",
    eventTypes: ["drop_goal"],
    researchSource: "Synthesis: three-point announcement",
    placeholders: ["minute", "player", "team"],
  },
  {
    templateKey: "penalty_goal_scored",
    outputType: "major_event",
    tone: "factual",
    body: "{minute}' Penalty goal — {player} slots it for {team}.",
    eventTypes: ["penalty_goal"],
    researchSource: "Synthesis: penalty goal pair pattern",
    placeholders: ["minute", "player", "team"],
  },
  {
    templateKey: "penalty_awarded",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' Penalty to {team} — {infringement}.",
    eventTypes: ["penalty"],
    researchSource: "User example + espn_scrum team+reason pattern",
    placeholders: ["minute", "team", "infringement"],
  },
  {
    templateKey: "penalty_awarded_territory",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' {team} win a penalty in {opponent} territory.",
    eventTypes: ["penalty"],
    researchSource: "Synthesis: territory context without inventing reason",
    placeholders: ["minute", "team", "opponent"],
  },
  {
    templateKey: "penalty_awarded_neutral",
    outputType: "referee_decision",
    tone: "neutral",
    body: "{minute}' The referee awards a penalty to {team}.",
    eventTypes: ["penalty"],
    researchSource: "Synthesis: when infringement unknown",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "score_update",
    outputType: "score_update",
    tone: "factual",
    body: "{home_team} {home_score}–{away_score} {away_team}.",
    eventTypes: ["score_update", "try", "conversion"],
    researchSource: "Synthesis: compact scoreline after events",
    placeholders: ["home_team", "home_score", "away_score", "away_team"],
  },
  {
    templateKey: "card_yellow",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' Yellow card for {player} ({team}).",
    eventTypes: ["card_yellow"],
    researchSource: "Synthesis: disciplinary immediacy",
    placeholders: ["minute", "player", "team"],
  },
  {
    templateKey: "card_red",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' Red card — {player} sent off for {team}.",
    eventTypes: ["card_red"],
    researchSource: "Synthesis: maximum prominence",
    placeholders: ["minute", "player", "team"],
  },
  {
    templateKey: "substitution_on",
    outputType: "personnel",
    tone: "neutral",
    body: "{minute}' Substitution for {team}: {player} on.",
    eventTypes: ["substitution"],
    researchSource: "Synthesis: sport365 type 1 structure",
    placeholders: ["minute", "team", "player"],
  },
  {
    templateKey: "injury_stoppage",
    outputType: "personnel",
    tone: "neutral",
    body: "{minute}' Play stopped for injury to {player} ({team}).",
    eventTypes: ["injury"],
    researchSource: "Synthesis: facts-only injury line",
    placeholders: ["minute", "player", "team"],
  },
  {
    templateKey: "tmo_review",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' TMO review underway.",
    eventTypes: ["tmo_decision"],
    researchSource: "Synthesis: two-phase TMO pattern",
    placeholders: ["minute"],
  },
  {
    templateKey: "tmo_decision",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' TMO decision: {decision}.",
    eventTypes: ["tmo_decision"],
    researchSource: "Synthesis: outcome only from facts",
    placeholders: ["minute", "decision"],
  },
  {
    templateKey: "referee_decision",
    outputType: "referee_decision",
    tone: "factual",
    body: "{minute}' Referee rules in favour of {team}.",
    eventTypes: ["referee_decision"],
    researchSource: "Synthesis: generic decision line",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "half_time",
    outputType: "period",
    tone: "factual",
    body: "Half-time: {home_team} {home_score}–{away_score} {away_team}.",
    eventTypes: ["half_time"],
    researchSource: "Synthesis: interval score",
    placeholders: ["home_team", "home_score", "away_score", "away_team"],
  },
  {
    templateKey: "full_time",
    outputType: "period",
    tone: "factual",
    body: "Full-time: {home_team} {home_score}–{away_score} {away_team}.",
    eventTypes: ["full_time"],
    researchSource: "Synthesis: final score",
    placeholders: ["home_team", "home_score", "away_score", "away_team"],
  },
  {
    templateKey: "full_time_summary",
    outputType: "period",
    tone: "analytical",
    body: "That's the final whistle — {home_team} {home_score}–{away_score} {away_team}.",
    eventTypes: ["full_time"],
    researchSource: "Synthesis: espn_scrum summary cadence without editorial copy",
    placeholders: ["home_team", "home_score", "away_score", "away_team"],
  },
  {
    templateKey: "scrum_in_progress",
    outputType: "phase_play_update",
    tone: "neutral",
    body: "{minute}' {team} scrum.",
    eventTypes: ["scrum"],
    researchSource: "Existing MVP + research brevity",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "scrum_feed",
    outputType: "phase_play_update",
    tone: "neutral",
    body: "{minute}' Scrum feed to {team}.",
    eventTypes: ["scrum"],
    researchSource: "Synthesis: feed attribution",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "lineout_in_progress",
    outputType: "phase_play_update",
    tone: "neutral",
    body: "{minute}' {team} lineout.",
    eventTypes: ["lineout"],
    researchSource: "Existing MVP",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "lineout_won",
    outputType: "phase_play_update",
    tone: "neutral",
    body: "{minute}' {team} secure the lineout.",
    eventTypes: ["lineout"],
    researchSource: "Synthesis: outcome when fact present",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "maul_in_progress",
    outputType: "phase_play_update",
    tone: "neutral",
    body: "{minute}' Driving maul from {team}.",
    eventTypes: ["maul"],
    researchSource: "Synthesis: low-frequency phase",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "turnover_won",
    outputType: "phase_play_update",
    tone: "factual",
    body: "{minute}' Turnover — {team} win possession.",
    eventTypes: ["turnover"],
    researchSource: "Synthesis: possession change",
    placeholders: ["minute", "team"],
  },
  {
    templateKey: "phase_pressure_opp22_a",
    outputType: "phase_play_update",
    tone: "analytical",
    body: "{minute}' {team} keep the pressure on inside the {opponent} 22.",
    eventTypes: ["phase_milestone"],
    researchSource: "Existing MVP phase set",
    placeholders: ["minute", "team", "opponent"],
  },
  {
    templateKey: "phase_pressure_opp22_b",
    outputType: "phase_play_update",
    tone: "analytical",
    body: "{minute}' {phase_count} phases now from {team} as they look for a gap.",
    eventTypes: ["phase_milestone"],
    researchSource: "Existing MVP",
    placeholders: ["minute", "phase_count", "team"],
  },
  {
    templateKey: "phase_pressure_opp22_c",
    outputType: "phase_play_update",
    tone: "analytical",
    body: "{minute}' The {opponent} defence is being made to work hard here.",
    eventTypes: ["phase_milestone"],
    researchSource: "Existing MVP",
    placeholders: ["minute", "opponent"],
  },
  {
    templateKey: "phase_pressure_opp22_d",
    outputType: "phase_play_update",
    tone: "analytical",
    body: "{minute}' {team} recycle again and stay on the front foot.",
    eventTypes: ["phase_milestone"],
    researchSource: "Existing MVP",
    placeholders: ["minute", "team"],
  },
];
