-- Nations Championship + remaining competition Creator Profiles (Lead + Analyst)
-- and division defaults so match Audio overrides can pick every competition scope.

INSERT INTO "audio_voice_profiles" (
  "slug", "display_name", "role", "accent", "locale",
  "organisation_label", "topic_label", "voice_style", "delivery_style",
  "provider", "openai_voice", "speed", "tone",
  "stability", "similarity_boost", "style_exaggeration",
  "competition_scope", "is_default", "status", "notes"
)
VALUES
  (
    'nations-championship-lead',
    'Nations Championship Lead',
    'lead',
    'international_english',
    'en',
    'International English',
    'Nations Championship',
    'television',
    'energetic',
    'openai',
    'onyx',
    1.04,
    'energetic',
    0.42,
    0.75,
    0.4,
    'nations_championship',
    true,
    'active',
    'Synthetic Nations Championship Lead — international broadcast English.'
  ),
  (
    'nations-championship-analyst',
    'Nations Championship Analyst',
    'analyst',
    'international_english',
    'en',
    'International English',
    'Nations Championship',
    'analyst',
    'balanced',
    'openai',
    'nova',
    0.98,
    'analytical',
    0.55,
    0.7,
    0.2,
    'nations_championship',
    true,
    'active',
    'Synthetic Nations Championship Analyst — international broadcast English.'
  ),
  (
    'urc-lead',
    'URC Lead',
    'lead',
    'british_english',
    'en-GB',
    'British English',
    'URC',
    'television',
    'balanced',
    'openai',
    'echo',
    1.03,
    'broadcast',
    0.42,
    0.75,
    0.35,
    'urc',
    true,
    'active',
    'Synthetic URC Lead — mixed-hemisphere broadcast English.'
  ),
  (
    'urc-analyst',
    'URC Analyst',
    'analyst',
    'british_english',
    'en-GB',
    'British English',
    'URC',
    'analyst',
    'balanced',
    'openai',
    'nova',
    0.98,
    'analytical',
    0.55,
    0.7,
    0.2,
    'urc',
    true,
    'active',
    'Synthetic URC Analyst — mixed-hemisphere broadcast English.'
  ),
  (
    'six-nations-lead',
    'Six Nations Lead',
    'lead',
    'british_english',
    'en-GB',
    'British English',
    'Six Nations',
    'television',
    'energetic',
    'openai',
    'onyx',
    1.04,
    'energetic',
    0.4,
    0.75,
    0.4,
    'six_nations',
    true,
    'active',
    'Synthetic Six Nations Lead — British / Irish broadcast English.'
  ),
  (
    'six-nations-analyst',
    'Six Nations Analyst',
    'analyst',
    'british_english',
    'en-GB',
    'British English',
    'Six Nations',
    'analyst',
    'balanced',
    'openai',
    'nova',
    0.97,
    'analytical',
    0.55,
    0.7,
    0.2,
    'six_nations',
    true,
    'active',
    'Synthetic Six Nations Analyst — British / Irish broadcast English.'
  ),
  (
    'super-rugby-lead',
    'Super Rugby Lead',
    'lead',
    'new_zealand_english',
    'en-NZ',
    'New Zealand English',
    'Super Rugby',
    'television',
    'energetic',
    'openai',
    'onyx',
    1.05,
    'energetic',
    0.4,
    0.75,
    0.42,
    'super_rugby',
    true,
    'active',
    'Synthetic Super Rugby Lead — NZ / AU broadcast English.'
  ),
  (
    'super-rugby-analyst',
    'Super Rugby Analyst',
    'analyst',
    'new_zealand_english',
    'en-NZ',
    'New Zealand English',
    'Super Rugby',
    'analyst',
    'balanced',
    'openai',
    'nova',
    0.97,
    'analytical',
    0.55,
    0.7,
    0.2,
    'super_rugby',
    true,
    'active',
    'Synthetic Super Rugby Analyst — NZ / AU broadcast English.'
  ),
  (
    'champions-cup-lead',
    'Champions Cup Lead',
    'lead',
    'british_english',
    'en-GB',
    'British English',
    'Champions Cup',
    'television',
    'balanced',
    'openai',
    'echo',
    1.03,
    'broadcast',
    0.42,
    0.75,
    0.35,
    'champions_cup',
    true,
    'active',
    'Synthetic Champions Cup Lead — European knockout broadcast English.'
  ),
  (
    'champions-cup-analyst',
    'Champions Cup Analyst',
    'analyst',
    'british_english',
    'en-GB',
    'British English',
    'Champions Cup',
    'analyst',
    'balanced',
    'openai',
    'nova',
    0.98,
    'analytical',
    0.55,
    0.7,
    0.2,
    'champions_cup',
    true,
    'active',
    'Synthetic Champions Cup Analyst — European knockout broadcast English.'
  )
ON CONFLICT ("slug") DO UPDATE SET
  "display_name" = EXCLUDED."display_name",
  "organisation_label" = EXCLUDED."organisation_label",
  "topic_label" = EXCLUDED."topic_label",
  "voice_style" = EXCLUDED."voice_style",
  "delivery_style" = EXCLUDED."delivery_style",
  "competition_scope" = EXCLUDED."competition_scope",
  "openai_voice" = COALESCE("audio_voice_profiles"."openai_voice", EXCLUDED."openai_voice"),
  "speed" = EXCLUDED."speed",
  "tone" = EXCLUDED."tone",
  "status" = 'active',
  "updated_at" = now();

INSERT INTO "audio_commentary_defaults" (
  "competition_scope",
  "label",
  "accent_label",
  "locale",
  "stadium_ambience_key",
  "lead_profile_id",
  "analyst_profile_id",
  "voice_style",
  "delivery_style",
  "optimise_dual_commentary",
  "emphasise_scoreboard",
  "presenter_count",
  "notes"
)
SELECT
  'nations_championship',
  'Nations Championship Duo',
  'International English',
  'en',
  'stadium_intl_generic',
  lead.id,
  analyst.id,
  'television',
  'energetic',
  true,
  true,
  2,
  'Default Lead + Analyst for World Rugby Nations Championship.'
FROM
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'nations-championship-lead' LIMIT 1) AS lead,
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'nations-championship-analyst' LIMIT 1) AS analyst
ON CONFLICT ("competition_scope") DO UPDATE SET
  "label" = EXCLUDED."label",
  "accent_label" = EXCLUDED."accent_label",
  "locale" = EXCLUDED."locale",
  "stadium_ambience_key" = COALESCE("audio_commentary_defaults"."stadium_ambience_key", EXCLUDED."stadium_ambience_key"),
  "lead_profile_id" = COALESCE("audio_commentary_defaults"."lead_profile_id", EXCLUDED."lead_profile_id"),
  "analyst_profile_id" = COALESCE("audio_commentary_defaults"."analyst_profile_id", EXCLUDED."analyst_profile_id"),
  "voice_style" = COALESCE("audio_commentary_defaults"."voice_style", EXCLUDED."voice_style"),
  "delivery_style" = COALESCE("audio_commentary_defaults"."delivery_style", EXCLUDED."delivery_style"),
  "updated_at" = now();

INSERT INTO "audio_commentary_defaults" (
  "competition_scope",
  "label",
  "accent_label",
  "locale",
  "stadium_ambience_key",
  "lead_profile_id",
  "analyst_profile_id",
  "voice_style",
  "delivery_style",
  "optimise_dual_commentary",
  "emphasise_scoreboard",
  "presenter_count",
  "notes"
)
SELECT
  'urc',
  'URC Duo',
  'British / mixed',
  'en-GB',
  'stadium_urc_generic',
  lead.id,
  analyst.id,
  'television',
  'balanced',
  true,
  true,
  2,
  'Default Lead + Analyst for United Rugby Championship.'
FROM
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'urc-lead' LIMIT 1) AS lead,
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'urc-analyst' LIMIT 1) AS analyst
ON CONFLICT ("competition_scope") DO UPDATE SET
  "label" = EXCLUDED."label",
  "accent_label" = EXCLUDED."accent_label",
  "locale" = EXCLUDED."locale",
  "stadium_ambience_key" = COALESCE("audio_commentary_defaults"."stadium_ambience_key", EXCLUDED."stadium_ambience_key"),
  "lead_profile_id" = COALESCE("audio_commentary_defaults"."lead_profile_id", EXCLUDED."lead_profile_id"),
  "analyst_profile_id" = COALESCE("audio_commentary_defaults"."analyst_profile_id", EXCLUDED."analyst_profile_id"),
  "voice_style" = COALESCE("audio_commentary_defaults"."voice_style", EXCLUDED."voice_style"),
  "delivery_style" = COALESCE("audio_commentary_defaults"."delivery_style", EXCLUDED."delivery_style"),
  "updated_at" = now();

INSERT INTO "audio_commentary_defaults" (
  "competition_scope",
  "label",
  "accent_label",
  "locale",
  "stadium_ambience_key",
  "lead_profile_id",
  "analyst_profile_id",
  "voice_style",
  "delivery_style",
  "optimise_dual_commentary",
  "emphasise_scoreboard",
  "presenter_count",
  "notes"
)
SELECT
  'six_nations',
  'Six Nations Duo',
  'British / Irish English',
  'en-GB',
  'stadium_uk_generic',
  lead.id,
  analyst.id,
  'television',
  'energetic',
  true,
  true,
  2,
  'Default Lead + Analyst for Six Nations.'
FROM
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'six-nations-lead' LIMIT 1) AS lead,
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'six-nations-analyst' LIMIT 1) AS analyst
ON CONFLICT ("competition_scope") DO UPDATE SET
  "label" = EXCLUDED."label",
  "accent_label" = EXCLUDED."accent_label",
  "locale" = EXCLUDED."locale",
  "stadium_ambience_key" = COALESCE("audio_commentary_defaults"."stadium_ambience_key", EXCLUDED."stadium_ambience_key"),
  "lead_profile_id" = COALESCE("audio_commentary_defaults"."lead_profile_id", EXCLUDED."lead_profile_id"),
  "analyst_profile_id" = COALESCE("audio_commentary_defaults"."analyst_profile_id", EXCLUDED."analyst_profile_id"),
  "voice_style" = COALESCE("audio_commentary_defaults"."voice_style", EXCLUDED."voice_style"),
  "delivery_style" = COALESCE("audio_commentary_defaults"."delivery_style", EXCLUDED."delivery_style"),
  "updated_at" = now();

INSERT INTO "audio_commentary_defaults" (
  "competition_scope",
  "label",
  "accent_label",
  "locale",
  "stadium_ambience_key",
  "lead_profile_id",
  "analyst_profile_id",
  "voice_style",
  "delivery_style",
  "optimise_dual_commentary",
  "emphasise_scoreboard",
  "presenter_count",
  "notes"
)
SELECT
  'super_rugby',
  'Super Rugby Duo',
  'New Zealand / Australian English',
  'en-NZ',
  'stadium_nz_generic',
  lead.id,
  analyst.id,
  'television',
  'energetic',
  true,
  true,
  2,
  'Default Lead + Analyst for Super Rugby.'
FROM
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'super-rugby-lead' LIMIT 1) AS lead,
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'super-rugby-analyst' LIMIT 1) AS analyst
ON CONFLICT ("competition_scope") DO UPDATE SET
  "label" = EXCLUDED."label",
  "accent_label" = EXCLUDED."accent_label",
  "locale" = EXCLUDED."locale",
  "stadium_ambience_key" = COALESCE("audio_commentary_defaults"."stadium_ambience_key", EXCLUDED."stadium_ambience_key"),
  "lead_profile_id" = COALESCE("audio_commentary_defaults"."lead_profile_id", EXCLUDED."lead_profile_id"),
  "analyst_profile_id" = COALESCE("audio_commentary_defaults"."analyst_profile_id", EXCLUDED."analyst_profile_id"),
  "voice_style" = COALESCE("audio_commentary_defaults"."voice_style", EXCLUDED."voice_style"),
  "delivery_style" = COALESCE("audio_commentary_defaults"."delivery_style", EXCLUDED."delivery_style"),
  "updated_at" = now();

INSERT INTO "audio_commentary_defaults" (
  "competition_scope",
  "label",
  "accent_label",
  "locale",
  "stadium_ambience_key",
  "lead_profile_id",
  "analyst_profile_id",
  "voice_style",
  "delivery_style",
  "optimise_dual_commentary",
  "emphasise_scoreboard",
  "presenter_count",
  "notes"
)
SELECT
  'champions_cup',
  'Champions Cup Duo',
  'British / European English',
  'en-GB',
  'stadium_eu_generic',
  lead.id,
  analyst.id,
  'television',
  'balanced',
  true,
  true,
  2,
  'Default Lead + Analyst for Investec Champions Cup.'
FROM
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'champions-cup-lead' LIMIT 1) AS lead,
  (SELECT "id" FROM "audio_voice_profiles" WHERE "slug" = 'champions-cup-analyst' LIMIT 1) AS analyst
ON CONFLICT ("competition_scope") DO UPDATE SET
  "label" = EXCLUDED."label",
  "accent_label" = EXCLUDED."accent_label",
  "locale" = EXCLUDED."locale",
  "stadium_ambience_key" = COALESCE("audio_commentary_defaults"."stadium_ambience_key", EXCLUDED."stadium_ambience_key"),
  "lead_profile_id" = COALESCE("audio_commentary_defaults"."lead_profile_id", EXCLUDED."lead_profile_id"),
  "analyst_profile_id" = COALESCE("audio_commentary_defaults"."analyst_profile_id", EXCLUDED."analyst_profile_id"),
  "voice_style" = COALESCE("audio_commentary_defaults"."voice_style", EXCLUDED."voice_style"),
  "delivery_style" = COALESCE("audio_commentary_defaults"."delivery_style", EXCLUDED."delivery_style"),
  "updated_at" = now();
