/**
 * Rugby365 competition catalog — taxonomy for CMS + future imports.
 * DB rows are only created/updated for competitions that are already populated
 * (seasons, fixtures or standings). Unpopulated catalog entries stay as roadmap.
 */

export type CompetitionGender = "men" | "women" | "mixed";
export type CompetitionAgeGroup = "senior" | "u20" | "u18" | "university" | "schools" | "mixed";
export type CompetitionFormat =
  | "league"
  | "cup"
  | "series"
  | "tour"
  | "championship"
  | "shield"
  | "sevens"
  | "playoff";
export type CompetitionLevel =
  | "international"
  | "continental"
  | "national_top"
  | "national_2"
  | "national_3"
  | "provincial"
  | "regional"
  | "club"
  | "collegiate"
  | "schools";
export type CompetitionSeasonStructure =
  | "northern_split"
  | "southern_calendar"
  | "tournament"
  | "touring"
  | "rolling";
export type CompetitionLifecycle = "current" | "former";

export type CompetitionCatalogEntry = {
  key: string;
  name: string;
  /** Names used to match existing DB competitions. */
  aliases: string[];
  group: string;
  country: string | null;
  region: string;
  gender: CompetitionGender;
  ageGroup: CompetitionAgeGroup;
  format: CompetitionFormat;
  level: CompetitionLevel;
  seasonStructure: CompetitionSeasonStructure;
  lifecycle: CompetitionLifecycle;
  competitionType: "domestic" | "international" | "world_cup" | "european";
};

function e(
  partial: Omit<CompetitionCatalogEntry, "aliases"> & { aliases?: string[] },
): CompetitionCatalogEntry {
  return { aliases: partial.aliases ?? [partial.name], ...partial };
}

export const COMPETITION_CATALOG: CompetitionCatalogEntry[] = [
  // —— International ——
  e({
    key: "rugby-world-cup",
    name: "Rugby World Cup",
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "senior",
    format: "tournament",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "world_cup",
  }),
  e({
    key: "six-nations",
    name: "Six Nations Championship",
    aliases: ["Six Nations Championship", "Six Nations", "Guinness Six Nations"],
    group: "International competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "rugby-championship",
    name: "The Rugby Championship",
    aliases: ["The Rugby Championship", "Rugby Championship", "TRC"],
    group: "International competitions",
    country: null,
    region: "southern_hemisphere",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "nations-championship",
    name: "Nations Championship",
    aliases: [
      "Nations Championship",
      "World Rugby Nations Championship",
      "World Rugby Nations Championship",
    ],
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "lions-tours",
    name: "British & Irish Lions Tours",
    aliases: ["British & Irish Lions Tours", "British and Irish Lions", "Lions Tour"],
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "senior",
    format: "tour",
    level: "international",
    seasonStructure: "touring",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "autumn-nations-series",
    name: "Autumn Nations Series",
    aliases: ["Autumn Nations Series", "Autumn Nations Cup", "Autumn Internationals"],
    group: "International competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "series",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "summer-nations-series",
    name: "Summer Nations Series",
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "senior",
    format: "series",
    level: "international",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "pacific-nations-cup",
    name: "World Rugby Pacific Nations Cup",
    group: "International competitions",
    country: null,
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "international",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "rugby-europe-championship",
    name: "Rugby Europe Championship",
    group: "International competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "rugby-europe-trophy",
    name: "Rugby Europe Trophy",
    group: "International competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "african-rugby-cup",
    name: "African Rugby Cup",
    aliases: ["African Rugby Cup", "Rugby Africa Cup"],
    group: "International competitions",
    country: null,
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "asia-rugby-championship",
    name: "Asia Rugby Championship",
    group: "International competitions",
    country: null,
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "south-american-rugby-championship",
    name: "South American Rugby Championship",
    group: "International competitions",
    country: null,
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "americas-rugby-championship",
    name: "Americas Rugby Championship",
    group: "International competitions",
    country: null,
    region: "americas",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "world-rugby-nations-cup",
    name: "World Rugby Nations Cup",
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "world-rugby-u20-championship",
    name: "World Rugby U20 Championship",
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "u20",
    format: "tournament",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "world-rugby-u20-trophy",
    name: "World Rugby U20 Trophy",
    group: "International competitions",
    country: null,
    region: "world",
    gender: "men",
    ageGroup: "u20",
    format: "tournament",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),

  // —— European club ——
  e({
    key: "champions-cup",
    name: "European Rugby Champions Cup",
    aliases: [
      "European Rugby Champions Cup",
      "Investec Champions Cup",
      "Champions Cup",
      "Heineken Champions Cup",
    ],
    group: "European club competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "european",
  }),
  e({
    key: "challenge-cup",
    name: "EPCR Challenge Cup",
    aliases: ["EPCR Challenge Cup", "Challenge Cup", "European Challenge Cup"],
    group: "European club competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "european",
  }),
  e({
    key: "urc",
    name: "United Rugby Championship",
    aliases: ["United Rugby Championship", "URC", "Pro14", "Celtic League"],
    group: "European club competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "european",
  }),
  e({
    key: "premiership-rugby-cup",
    name: "Premiership Rugby Cup",
    group: "European club competitions",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "anglo-welsh-cup",
    name: "Anglo-Welsh Cup",
    group: "European club competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "former",
    competitionType: "european",
  }),
  e({
    key: "continental-club-rugby-league",
    name: "Continental Club Rugby League",
    group: "European club competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "european",
  }),
  e({
    key: "rugby-europe-super-cup",
    name: "Rugby Europe Super Cup",
    group: "European club competitions",
    country: null,
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "european",
  }),

  // —— England ——
  e({
    key: "premiership-rugby",
    name: "Premiership Rugby",
    aliases: ["Premiership Rugby", "Premiership", "Gallagher Premiership", "English Premiership"],
    group: "England",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "rfu-championship",
    name: "RFU Championship",
    aliases: ["RFU Championship", "Championship", "English Championship"],
    group: "England",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "national-league-1",
    name: "National League 1",
    group: "England",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "national-league-2",
    name: "National League 2",
    group: "England",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "rfu-championship-cup",
    name: "RFU Championship Cup",
    group: "England",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "county-championship",
    name: "County Championship",
    group: "England",
    country: "England",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "regional",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),

  // —— France ——
  e({
    key: "top-14",
    name: "Top 14",
    aliases: ["Top 14", "French Top 14"],
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "pro-d2",
    name: "Pro D2",
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "nationale",
    name: "Nationale",
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "nationale-2",
    name: "Nationale 2",
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "federale-1",
    name: "Fédérale 1",
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "club",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "federale-2",
    name: "Fédérale 2",
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "club",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "federale-3",
    name: "Fédérale 3",
    group: "France",
    country: "France",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "club",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),

  // —— Ireland / Scotland / Wales / Italy (club) ——
  e({
    key: "all-ireland-league",
    name: "All-Ireland League",
    group: "Ireland",
    country: "Ireland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "leinster-senior-league",
    name: "Leinster Senior League",
    group: "Ireland",
    country: "Ireland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "munster-senior-league",
    name: "Munster Senior League",
    group: "Ireland",
    country: "Ireland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "ulster-championship",
    name: "Ulster Championship",
    group: "Ireland",
    country: "Ireland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "provincial",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "connacht-senior-league",
    name: "Connacht Senior League",
    group: "Ireland",
    country: "Ireland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "all-ireland-cup",
    name: "All-Ireland Cup",
    group: "Ireland",
    country: "Ireland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "scottish-premiership",
    name: "Scottish Premiership",
    group: "Scotland",
    country: "Scotland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "scottish-national-league",
    name: "Scottish National League",
    group: "Scotland",
    country: "Scotland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "scottish-cup",
    name: "Scottish Cup",
    group: "Scotland",
    country: "Scotland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "super-series",
    name: "Super Series",
    group: "Scotland",
    country: "Scotland",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "super-rygbi-cymru",
    name: "Super Rygbi Cymru",
    group: "Wales",
    country: "Wales",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "welsh-championship",
    name: "Welsh Championship",
    group: "Wales",
    country: "Wales",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "welsh-national-leagues",
    name: "Welsh National Leagues",
    group: "Wales",
    country: "Wales",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "welsh-premiership-cup",
    name: "Welsh Premiership Cup",
    group: "Wales",
    country: "Wales",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "serie-a-elite",
    name: "Serie A Elite",
    group: "Italy",
    country: "Italy",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "serie-a",
    name: "Serie A",
    group: "Italy",
    country: "Italy",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "serie-b",
    name: "Serie B",
    group: "Italy",
    country: "Italy",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "coppa-italia",
    name: "Coppa Italia",
    group: "Italy",
    country: "Italy",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),

  // —— Iberia / Eastern Europe (compact) ——
  e({
    key: "division-de-honor",
    name: "División de Honor",
    group: "Spain",
    country: "Spain",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "division-de-honor-b",
    name: "División de Honor B",
    group: "Spain",
    country: "Spain",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "copa-del-rey",
    name: "Copa del Rey de Rugby",
    group: "Spain",
    country: "Spain",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "supercopa-espana",
    name: "Supercopa de España",
    group: "Spain",
    country: "Spain",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "campeonato-nacional-portugal",
    name: "Campeonato Nacional de Rugby",
    group: "Portugal",
    country: "Portugal",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "taca-portugal",
    name: "Taça de Portugal",
    group: "Portugal",
    country: "Portugal",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "supertaca-portugal",
    name: "Supertaça de Portugal",
    group: "Portugal",
    country: "Portugal",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "didi-10",
    name: "Didi 10",
    group: "Georgia",
    country: "Georgia",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "georgian-rugby-cup",
    name: "Georgian Rugby Cup",
    group: "Georgia",
    country: "Georgia",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "liga-nationala-romania",
    name: "Liga Națională de Rugby",
    group: "Romania",
    country: "Romania",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "romanian-rugby-cup",
    name: "Romanian Rugby Cup",
    group: "Romania",
    country: "Romania",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "rugby-bundesliga",
    name: "Rugby-Bundesliga",
    group: "Germany",
    country: "Germany",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "german-rugby-cup",
    name: "German Rugby Cup",
    group: "Germany",
    country: "Germany",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "ereklasse",
    name: "Ereklasse",
    group: "Netherlands",
    country: "Netherlands",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "eerste-klasse",
    name: "Eerste Klasse",
    group: "Netherlands",
    country: "Netherlands",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "dutch-rugby-cup",
    name: "Dutch Rugby Cup",
    group: "Netherlands",
    country: "Netherlands",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "belgian-elite-league",
    name: "Belgian Elite League",
    group: "Belgium",
    country: "Belgium",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "belgian-rugby-cup",
    name: "Belgian Rugby Cup",
    group: "Belgium",
    country: "Belgium",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "russian-rugby-championship",
    name: "Russian Rugby Championship",
    group: "Russia",
    country: "Russia",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "russian-rugby-cup",
    name: "Russian Rugby Cup",
    group: "Russia",
    country: "Russia",
    region: "europe",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),

  // —— Southern Hemisphere club ——
  e({
    key: "super-rugby",
    name: "Super Rugby",
    aliases: ["Super Rugby"],
    group: "Southern Hemisphere club competitions",
    country: null,
    region: "southern_hemisphere",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-pacific",
    name: "Super Rugby Pacific",
    aliases: ["Super Rugby Pacific"],
    group: "Southern Hemisphere club competitions",
    country: null,
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-americas",
    name: "Super Rugby Americas",
    aliases: ["Super Rugby Americas", "Súper Liga Americana de Rugby"],
    group: "Southern Hemisphere club competitions",
    country: null,
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-aupiki",
    name: "Super Rugby Aupiki",
    group: "Women’s major competitions",
    country: "New Zealand",
    region: "pacific",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-au",
    name: "Super Rugby AU",
    group: "Southern Hemisphere club competitions",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-aotearoa",
    name: "Super Rugby Aotearoa",
    group: "Southern Hemisphere club competitions",
    country: "New Zealand",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-unlocked",
    name: "Super Rugby Unlocked",
    group: "Southern Hemisphere club competitions",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "former",
    competitionType: "domestic",
  }),

  // —— South Africa ——
  e({
    key: "currie-cup-premier",
    name: "Currie Cup Premier Division",
    aliases: ["Currie Cup Premier Division", "Currie Cup", "Currie Cup PD"],
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "currie-cup-first",
    name: "Currie Cup First Division",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "sa-cup",
    name: "SA Cup",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "varsity-cup",
    name: "Varsity Cup",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "university",
    format: "league",
    level: "collegiate",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "varsity-shield",
    name: "Varsity Shield",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "university",
    format: "league",
    level: "collegiate",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "gold-cup",
    name: "Gold Cup",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "club",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "craven-week",
    name: "Craven Week",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "schools",
    format: "tournament",
    level: "schools",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "mzansi-challenge",
    name: "Mzansi Challenge",
    group: "South Africa",
    country: "South Africa",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "southern_calendar",
    lifecycle: "former",
    competitionType: "domestic",
  }),

  // —— NZ / Australia ——
  e({
    key: "npc",
    name: "National Provincial Championship",
    aliases: ["National Provincial Championship", "NPC", "Bunnings NPC"],
    group: "New Zealand",
    country: "New Zealand",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "heartland-championship",
    name: "Heartland Championship",
    group: "New Zealand",
    country: "New Zealand",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "ranfurly-shield",
    name: "Ranfurly Shield",
    group: "New Zealand",
    country: "New Zealand",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "shield",
    level: "provincial",
    seasonStructure: "rolling",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "north-versus-south",
    name: "North versus South",
    group: "New Zealand",
    country: "New Zealand",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "series",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "shute-shield",
    name: "Shute Shield",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "hospital-cup",
    name: "Hospital Cup",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "john-i-dent-cup",
    name: "John I Dent Cup",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "fortescue-premier-grade",
    name: "Fortescue Premier Grade",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "dewar-shield",
    name: "Dewar Shield",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "shield",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "sa-premier-grade",
    name: "South Australian Premier Grade",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "tasmanian-premiership",
    name: "Tasmanian Rugby Premiership",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "nrc",
    name: "National Rugby Championship",
    group: "Australia",
    country: "Australia",
    region: "oceania",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "former",
    competitionType: "domestic",
  }),

  // —— Argentina / Americas / Pacific / Asia / Africa (key) ——
  e({
    key: "nacional-de-clubes",
    name: "Nacional de Clubes",
    aliases: ["Nacional de Clubes", "Argentine Nacional de Clubes"],
    group: "Argentina",
    country: "Argentina",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "torneo-urba",
    name: "Torneo de la URBA",
    aliases: ["Torneo de la URBA", "URBA Top 12"],
    group: "Argentina",
    country: "Argentina",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "torneo-del-interior",
    name: "Torneo del Interior",
    group: "Argentina",
    country: "Argentina",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "major-league-rugby",
    name: "Major League Rugby",
    group: "United States",
    country: "United States",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "usa-d1",
    name: "USA Rugby Division 1",
    group: "United States",
    country: "United States",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "usa-d2",
    name: "USA Rugby Division 2",
    group: "United States",
    country: "United States",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "usa-d3",
    name: "USA Rugby Division 3",
    group: "United States",
    country: "United States",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "club",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "american-rugby-premiership",
    name: "American Rugby Premiership",
    group: "United States",
    country: "United States",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "collegiate-rugby-championship",
    name: "Collegiate Rugby Championship",
    group: "United States",
    country: "United States",
    region: "north_america",
    gender: "men",
    ageGroup: "university",
    format: "tournament",
    level: "collegiate",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "canadian-rugby-championship",
    name: "Canadian Rugby Championship",
    group: "Canada",
    country: "Canada",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "bc-premier-league",
    name: "British Columbia Premier League",
    group: "Canada",
    country: "Canada",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "ontario-marshall",
    name: "Ontario Marshall Premiership",
    group: "Canada",
    country: "Canada",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "provincial",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "canadian-club-championship",
    name: "Canadian Rugby Club Championship",
    group: "Canada",
    country: "Canada",
    region: "north_america",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "club",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "brazil-championship",
    name: "Brazilian Rugby Championship",
    group: "South America",
    country: "Brazil",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "chile-championship",
    name: "Chilean National Rugby Championship",
    group: "South America",
    country: "Chile",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "campeonato-uruguayo",
    name: "Uruguayan Campeonato Uruguayo",
    group: "South America",
    country: "Uruguay",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "paraguay-championship",
    name: "Paraguayan Rugby Championship",
    group: "South America",
    country: "Paraguay",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "colombia-championship",
    name: "Colombian National Rugby Championship",
    group: "South America",
    country: "Colombia",
    region: "south_america",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "skipper-cup",
    name: "Skipper Cup",
    group: "Pacific Islands",
    country: "Fiji",
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "farebrother-sullivan",
    name: "Farebrother-Sullivan Trophy",
    group: "Pacific Islands",
    country: "Fiji",
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "shield",
    level: "national_top",
    seasonStructure: "rolling",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "digicel-escott",
    name: "Digicel Escott Shield",
    group: "Pacific Islands",
    country: "Fiji",
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "shield",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "samoa-npc",
    name: "Samoa National Provincial Championship",
    group: "Pacific Islands",
    country: "Samoa",
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "provincial",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "lakapi-championship",
    name: "Lakapi Championship",
    group: "Pacific Islands",
    country: "Tonga",
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "pacific-rugby-cup",
    name: "Pacific Rugby Cup",
    group: "Pacific Islands",
    country: null,
    region: "pacific",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "japan-league-one-d1",
    name: "Japan Rugby League One Division 1",
    aliases: ["Japan Rugby League One Division 1", "League One", "Top League"],
    group: "Japan",
    country: "Japan",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "japan-league-one-d2",
    name: "Japan Rugby League One Division 2",
    group: "Japan",
    country: "Japan",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "japan-league-one-d3",
    name: "Japan Rugby League One Division 3",
    group: "Japan",
    country: "Japan",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "all-japan-championship",
    name: "All-Japan Rugby Championship",
    group: "Japan",
    country: "Japan",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "top-league",
    name: "Top League",
    group: "Japan",
    country: "Japan",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "former",
    competitionType: "domestic",
  }),
  e({
    key: "hong-kong-premiership",
    name: "Hong Kong Premiership",
    group: "Hong Kong",
    country: "Hong Kong",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "hong-kong-premiership-a",
    name: "Hong Kong Premiership A",
    group: "Hong Kong",
    country: "Hong Kong",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_2",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "hong-kong-championship",
    name: "Hong Kong Championship",
    group: "Hong Kong",
    country: "Hong Kong",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "national_3",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "korea-rugby-league",
    name: "Korea Rugby League",
    group: "South Korea",
    country: "South Korea",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "korea-national-sports",
    name: "Korea National Sports Festival",
    group: "South Korea",
    country: "South Korea",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "tournament",
    level: "national_top",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "sri-lanka-league",
    name: "Sri Lanka Rugby League",
    group: "Sri Lanka",
    country: "Sri Lanka",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "clifford-cup",
    name: "Clifford Cup",
    group: "Sri Lanka",
    country: "Sri Lanka",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "all-india-championship",
    name: "All India Rugby Championship",
    group: "India",
    country: "India",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "national_top",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "india-sevens",
    name: "Indian National Rugby Sevens Championship",
    group: "India",
    country: "India",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "sevens",
    level: "national_top",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "malaysia-league",
    name: "Malaysia Rugby League",
    group: "Malaysia",
    country: "Malaysia",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "agongs-cup",
    name: "Agong’s Cup",
    group: "Malaysia",
    country: "Malaysia",
    region: "asia",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "rugby-africa-cup",
    name: "Rugby Africa Cup",
    group: "Africa",
    country: null,
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "rugby-africa-trophy",
    name: "Rugby Africa Trophy",
    group: "Africa",
    country: null,
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "rugby-africa-regional",
    name: "Rugby Africa Regional Challenge",
    group: "Africa",
    country: null,
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "kenya-cup",
    name: "Kenya Cup",
    group: "Africa",
    country: "Kenya",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "kenya-enterprise-cup",
    name: "Kenya Enterprise Cup",
    group: "Africa",
    country: "Kenya",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "uganda-premiership",
    name: "Uganda Rugby Premiership",
    group: "Africa",
    country: "Uganda",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "uganda-cup",
    name: "Uganda Cup",
    group: "Africa",
    country: "Uganda",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "cup",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "zimbabwe-challenge",
    name: "Zimbabwe Rugby Challenge",
    group: "Africa",
    country: "Zimbabwe",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "tunisia-championship",
    name: "Tunisia Rugby Championship",
    group: "Africa",
    country: "Tunisia",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "morocco-championship",
    name: "Morocco Rugby Championship",
    group: "Africa",
    country: "Morocco",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "madagascar-top-20",
    name: "Madagascar Top 20",
    group: "Africa",
    country: "Madagascar",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "namibia-premier",
    name: "Namibia Rugby Premier League",
    group: "Africa",
    country: "Namibia",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "ghana-club",
    name: "Ghana Rugby Club Championship",
    group: "Africa",
    country: "Ghana",
    region: "africa",
    gender: "men",
    ageGroup: "senior",
    format: "championship",
    level: "club",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),

  // —— Women’s ——
  e({
    key: "womens-rugby-world-cup",
    name: "Women’s Rugby World Cup",
    group: "Women’s major competitions",
    country: null,
    region: "world",
    gender: "women",
    ageGroup: "senior",
    format: "tournament",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "world_cup",
  }),
  e({
    key: "womens-six-nations",
    name: "Women’s Six Nations",
    group: "Women’s major competitions",
    country: null,
    region: "europe",
    gender: "women",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "wxv-1",
    name: "WXV 1",
    group: "Women’s major competitions",
    country: null,
    region: "world",
    gender: "women",
    ageGroup: "senior",
    format: "series",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "wxv-2",
    name: "WXV 2",
    group: "Women’s major competitions",
    country: null,
    region: "world",
    gender: "women",
    ageGroup: "senior",
    format: "series",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "wxv-3",
    name: "WXV 3",
    group: "Women’s major competitions",
    country: null,
    region: "world",
    gender: "women",
    ageGroup: "senior",
    format: "series",
    level: "international",
    seasonStructure: "tournament",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "pacific-four",
    name: "Pacific Four Series",
    group: "Women’s major competitions",
    country: null,
    region: "pacific",
    gender: "women",
    ageGroup: "senior",
    format: "series",
    level: "international",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "womens-rugby-europe",
    name: "Women’s Rugby Europe Championship",
    group: "Women’s major competitions",
    country: null,
    region: "europe",
    gender: "women",
    ageGroup: "senior",
    format: "championship",
    level: "international",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "international",
  }),
  e({
    key: "pwr",
    name: "Premiership Women’s Rugby",
    group: "Women’s major competitions",
    country: "England",
    region: "europe",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "celtic-challenge",
    name: "Celtic Challenge",
    group: "Women’s major competitions",
    country: null,
    region: "europe",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "european",
  }),
  e({
    key: "elite-1-feminine",
    name: "Élite 1 Féminine",
    group: "Women’s major competitions",
    country: "France",
    region: "europe",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "super-rugby-womens",
    name: "Super Rugby Women’s",
    group: "Women’s major competitions",
    country: null,
    region: "southern_hemisphere",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "continental",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "womens-premier-sa",
    name: "Women’s Premier Division",
    group: "Women’s major competitions",
    country: "South Africa",
    region: "africa",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "southern_calendar",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "womens-japan",
    name: "Women’s Japan Rugby Championship",
    group: "Women’s major competitions",
    country: "Japan",
    region: "asia",
    gender: "women",
    ageGroup: "senior",
    format: "championship",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
  e({
    key: "womens-elite-usa",
    name: "Women’s Elite Rugby",
    group: "Women’s major competitions",
    country: "United States",
    region: "north_america",
    gender: "women",
    ageGroup: "senior",
    format: "league",
    level: "national_top",
    seasonStructure: "northern_split",
    lifecycle: "current",
    competitionType: "domestic",
  }),
];

export function normalizeCompetitionMatchKey(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function findCatalogEntryForCompetitionName(
  name: string,
): CompetitionCatalogEntry | null {
  const key = normalizeCompetitionMatchKey(name);
  // Exact alias match first (prefer longer aliases to avoid NPC ⊂ something).
  let best: { entry: CompetitionCatalogEntry; len: number } | null = null;
  for (const entry of COMPETITION_CATALOG) {
    for (const alias of entry.aliases) {
      const a = normalizeCompetitionMatchKey(alias);
      if (a === key) {
        if (!best || a.length > best.len) best = { entry, len: a.length };
      }
    }
  }
  if (best) return best.entry;

  // Short exact aliases only (NPC, URC) — no fuzzy contains.
  for (const entry of COMPETITION_CATALOG) {
    for (const alias of entry.aliases) {
      const a = normalizeCompetitionMatchKey(alias);
      if (a.length <= 4 && a === key) return entry;
    }
  }
  return null;
}

export function groupCompetitionCatalog(): Map<string, CompetitionCatalogEntry[]> {
  const map = new Map<string, CompetitionCatalogEntry[]>();
  for (const entry of COMPETITION_CATALOG) {
    const list = map.get(entry.group) ?? [];
    list.push(entry);
    map.set(entry.group, list);
  }
  return map;
}
