import type { RefereeDashboardModel } from "./referee-dashboard-types";

/** Wikimedia Commons portrait (CC). Swap this URL when a licensed studio still is available. */
export const REFEREE_PORTRAIT_PLACEHOLDER =
  "https://upload.wikimedia.org/wikipedia/commons/2/26/Andrew_Brace_2021.jpg";

const ready = {
  radar: "ready",
  career: "ready",
  disciplinary: "ready",
  ratingTrend: "ready",
  insights: "ready",
  breakdown: "ready",
  matches: "ready",
  season: "ready",
  next: "ready",
} as const;

/**
 * Sample analytics for the referee dashboard until match-official APIs land.
 * Identity fields are overwritten from the live referee profile when present.
 */
/** Sample analytics for the referee dashboard until match-official APIs land. */
export const REFEREE_DASHBOARD_ANALYTICS_TEMPLATE: RefereeDashboardModel = {
  isMockAnalytics: true,
  slug: "",
  name: "",
  countryName: "",
  flagUrl: null,
  roleBadge: "International Rugby Referee",
  portraitUrl: null,
  bio: {
    nationality: "—",
    dateOfBirth: "—",
    worldRugbyDebut: "—",
    refereeStyle: "Communication · Consistency · Control",
    preferredRole: "Centre referee",
    union: "—",
    profession: "—",
  },
  overallRating: 0,
  worldRank: 0,
  totalMatches: 0,
  internationalMatches: 0,
  formLast10: [
    "positive",
    "positive",
    "positive",
    "positive",
    "below",
    "positive",
    "positive",
    "positive",
    "positive",
    "positive",
  ],
  radar: [
    { category: "Consistency", referee: 88, eliteAverage: 79 },
    { category: "Game Management", referee: 91, eliteAverage: 80 },
    { category: "Communication", referee: 90, eliteAverage: 81 },
    { category: "Decision Accuracy", referee: 84, eliteAverage: 78 },
    { category: "Control & Discipline", referee: 86, eliteAverage: 77 },
    { category: "Advantage Application", referee: 83, eliteAverage: 76 },
  ],
  careerStats: [
    { key: "matches", label: "Matches", value: "0" },
    { key: "internationals", label: "International matches", value: "0" },
    { key: "tests", label: "Tests", value: "0" },
    { key: "tournaments", label: "Tournaments", value: "0" },
    { key: "ycAvg", label: "Yellow cards avg", value: "1.7", hint: "per match" },
    { key: "rcAvg", label: "Red cards avg", value: "0.08", hint: "per match" },
    { key: "penAvg", label: "Penalties awarded avg", value: "18.4", hint: "per match" },
    { key: "scrumPenAvg", label: "Scrum penalties avg", value: "4.1", hint: "per match" },
    { key: "lineoutPenAvg", label: "Lineout penalties avg", value: "2.6", hint: "per match" },
    { key: "advAvg", label: "Advantage used avg", value: "9.2", hint: "per match" },
    { key: "tmoAvg", label: "TMO referrals avg", value: "2.1", hint: "per match" },
    { key: "accuracy", label: "Decisions correct", value: "93%" },
  ],
  disciplinary: [
    { key: "yellow", label: "Yellow cards", perMatch: 1.7, careerTotal: 312 },
    { key: "red", label: "Red cards", perMatch: 0.08, careerTotal: 15 },
    { key: "sinbin", label: "Sin bins", perMatch: 0.4, careerTotal: 74 },
  ],
  ratingHistory: [
    { month: "Oct 24", rating: 83.1 },
    { month: "Nov 24", rating: 83.8 },
    { month: "Dec 24", rating: 84.0 },
    { month: "Jan 25", rating: 84.6 },
    { month: "Feb 25", rating: 85.1 },
    { month: "Mar 25", rating: 84.4 },
    { month: "Apr 25", rating: 85.0 },
    { month: "May 25", rating: 85.7 },
    { month: "Jun 25", rating: 85.2 },
    { month: "Jul 25", rating: 85.9 },
    { month: "Aug 25", rating: 86.1 },
    { month: "Sep 25", rating: 85.6 },
    { month: "Oct 25", rating: 86.0 },
    { month: "Nov 25", rating: 86.8 },
    { month: "Dec 25", rating: 86.2 },
    { month: "Jan 26", rating: 86.5 },
    { month: "Feb 26", rating: 85.9 },
    { month: "Mar 26", rating: 86.7 },
    { month: "Apr 26", rating: 86.1 },
    { month: "May 26", rating: 86.9 },
    { month: "Jun 26", rating: 86.4 },
    { month: "Jul 26", rating: 86.8 },
    { month: "Aug 26", rating: 86.2 },
    { month: "Sep 26", rating: 86.4 },
  ],
  strengths: [
    { label: "Game management", detail: "Keeps tempo high without losing set-piece control." },
    { label: "Player communication", detail: "Clear explanations at the breakdown and in the sin-bin process." },
    { label: "Advantage application", detail: "Lets contests breathe, then returns with a fair penalty." },
  ],
  developmentAreas: [
    { label: "High-tackle consistency", detail: "Head-contact thresholds still vary under fatigue in the last quarter." },
    { label: "Scrum reset time", detail: "A few long resets in wet Tests dragged game time." },
  ],
  matchTypeBreakdown: [
    { competition: "Test rugby", matches: 42, avgRating: 87.1 },
    { competition: "Six Nations", matches: 14, avgRating: 86.8 },
    { competition: "Rugby World Cup", matches: 8, avgRating: 88.2 },
    { competition: "United Rugby Championship", matches: 71, avgRating: 85.4 },
    { competition: "Investec Champions Cup", matches: 29, avgRating: 86.0 },
    { competition: "EPCR Challenge Cup", matches: 12, avgRating: 84.7 },
  ],
  recentMatches: [
    {
      id: "mock-1",
      dateLabel: "14 Mar 2026",
      fixtureLabel: "Ireland 22 - 20 France",
      href: "/matches/ireland-v-france-2026-03-14",
      competition: "Six Nations",
      rating: 88.1,
      yellowCards: 2,
      redCards: 0,
      isMock: true,
      kickoffAtIso: "2026-03-14T15:00:00.000Z",
      homeTeamName: "Ireland",
      awayTeamName: "France",
      homeScore: 22,
      awayScore: 20,
      homeCrestUrl: "https://flagcdn.com/w40/ie.png",
      awayCrestUrl: "https://flagcdn.com/w40/fr.png",
    },
    {
      id: "mock-2",
      dateLabel: "1 Mar 2026",
      fixtureLabel: "Leinster 31 - 22 Toulouse",
      href: "/matches/leinster-v-toulouse-2026-03-01",
      competition: "Champions Cup",
      rating: 86.4,
      yellowCards: 1,
      redCards: 0,
      isMock: true,
      kickoffAtIso: "2026-03-01T15:00:00.000Z",
      homeTeamName: "Leinster",
      awayTeamName: "Toulouse",
      homeScore: 31,
      awayScore: 22,
      homeCrestUrl: null,
      awayCrestUrl: null,
    },
    {
      id: "mock-3",
      dateLabel: "15 Feb 2026",
      fixtureLabel: "Wales 18 - 27 Scotland",
      href: "/matches/wales-v-scotland-2026-02-15",
      competition: "Six Nations",
      rating: 85.9,
      yellowCards: 3,
      redCards: 0,
      isMock: true,
      kickoffAtIso: "2026-02-15T15:00:00.000Z",
      homeTeamName: "Wales",
      awayTeamName: "Scotland",
      homeScore: 18,
      awayScore: 27,
      homeCrestUrl: "https://flagcdn.com/w40/gb-wls.png",
      awayCrestUrl: "https://flagcdn.com/w40/gb-sct.png",
    },
    {
      id: "mock-4",
      dateLabel: "25 Jan 2026",
      fixtureLabel: "Munster 24 - 21 Stormers",
      href: "/matches/munster-v-stormers-2026-01-25",
      competition: "URC",
      rating: 84.2,
      yellowCards: 2,
      redCards: 1,
      isMock: true,
      kickoffAtIso: "2026-01-25T15:00:00.000Z",
      homeTeamName: "Munster",
      awayTeamName: "Stormers",
      homeScore: 24,
      awayScore: 21,
      homeCrestUrl: null,
      awayCrestUrl: null,
    },
    {
      id: "mock-5",
      dateLabel: "11 Jan 2026",
      fixtureLabel: "Glasgow 19 - 17 Bulls",
      href: "/matches/glasgow-v-bulls-2026-01-11",
      competition: "URC",
      rating: 85.5,
      yellowCards: 1,
      redCards: 0,
      isMock: true,
      kickoffAtIso: "2026-01-11T15:00:00.000Z",
      homeTeamName: "Glasgow",
      awayTeamName: "Bulls",
      homeScore: 19,
      awayScore: 17,
      homeCrestUrl: null,
      awayCrestUrl: null,
    },
  ],
  seasonLabel: "2025/26",
  seasonSummary: [
    { key: "matches", label: "Matches", value: "18" },
    { key: "avg", label: "Avg rating", value: "86.1" },
    { key: "tests", label: "Tests", value: "6" },
    { key: "yc", label: "YC / game", value: "1.6" },
    { key: "pen", label: "Pens / game", value: "17.8" },
    { key: "tmo", label: "TMO / game", value: "2.0" },
  ],
  nextAppointment: null,
  highlights: [
    { label: "World Cup panel", detail: "Appointed to Rugby World Cup tournaments." },
    { label: "International Tests", detail: "World Rugby panel centre referee." },
    { label: "European Cups", detail: "Champions Cup and Challenge Cup appointments." },
    { label: "Club rugby", detail: "Domestic championship appointments." },
  ],
  about: "",
  sectionStatus: ready,
};

/** @deprecated Use REFEREE_DASHBOARD_ANALYTICS_TEMPLATE — kept for existing tests. */
export const ANDREW_BRACE_DASHBOARD_MOCK = REFEREE_DASHBOARD_ANALYTICS_TEMPLATE;
